//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Mangement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id_Bill { get; set; }
        public int Paid { get; set; }
        public int Rest { get; set; }
        public System.DateTime Date { get; set; }
        public int Id_S { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
