//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Mangement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id_Session { get; set; }
        public string Day_S { get; set; }
        public string Time_S { get; set; }
        public int Id_Class { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
