//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Mangement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Regisrtation
    {
        public int Id_SR { get; set; }
        public int Id_S { get; set; }
        public int Id_Class { get; set; }
        public System.DateTime Date_Reg { get; set; }
        public int Value_Reg { get; set; }
        public string Note_Reg { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
